services:
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes: 
      - mysql_volume_gt:/var/lib/mysql

  go-backend:
    build: .
    volumes:
      - ./:/app
    ports:
     - ${DOCKER_SERVER_PORT}

volumes:
  mysql_volume_gt:

networks:
  network: