services:
  mysql-db:
    image: mysql:latest
    container_name: ${DB_CONTAINER}
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_HOST_PORT}:${DB_REMOTE_PORT}
    volumes: 
      - mysql_volume_gt:/var/lib/mysql

  go-backend:
    container_name: ${API_CONTAINER}
    build: .
    volumes:
      - ./:/app
    ports:
     - ${API_HOST_PORT}:${API_REMOTE_PORT}

volumes:
  mysql_volume_gt:

networks:
  network: